### ISSUE TITLE
import `openai-function-calling-tools` 模块后报错 Module not found.

### ISSUE THREAD

**Issue by shangdev** [JohannLai/openai-function-calling-tools#2]
![image](https://github.com/JohannLai/openai-function-calling-tools/assets/15621520/7ed6c9cb-95d8-4f77-ae65-0cf0c1c0a5b1)

如图，移除 import 不报错，加上就报错.

**Comment by shangdev** [comment]
用的Umi框架，好像和这个库不兼容？

**Comment by JohannLai** [comment]
Thank you, feedback received, currently I am in a Node environment, and today I improved the configuration of the browser.文档反馈收到，目前我是在 Node 环境下开发，我今天完善 browser 的配置

**Comment by shangdev** [comment]
@JohannLai 请问这个问题好像没解决吧？今天拉了最新的v3还有报错
